/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      'xs': '320px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    spacing: {
      '0': '0',
      'px': '1px',
      '0.5': 'clamp(0.125rem, 0.5vw, 0.5rem)',
      '1': 'clamp(0.25rem, 1vw, 1rem)',
      '2': 'clamp(0.5rem, 1.5vw, 1.5rem)',
      '3': 'clamp(0.75rem, 2vw, 2rem)',
      '4': 'clamp(1rem, 2.5vw, 2.5rem)',
      '6': 'clamp(1.5rem, 3vw, 3rem)',
      '8': 'clamp(2rem, 4vw, 4rem)',
      '12': 'clamp(3rem, 5vw, 5rem)',
      '16': 'clamp(4rem, 6vw, 6rem)',
    },
    fontSize: {
      'xs': ['clamp(0.75rem, 1.5vw, 0.875rem)', { lineHeight: '1.5' }],
      'sm': ['clamp(0.875rem, 1.75vw, 1rem)', { lineHeight: '1.6' }],
      'base': ['clamp(1rem, 2vw, 1.125rem)', { lineHeight: '1.7' }],
      'lg': ['clamp(1.125rem, 2.25vw, 1.375rem)', { lineHeight: '1.8' }],
      'xl': ['clamp(1.25rem, 2.5vw, 1.5rem)', { lineHeight: '1.8' }],
      '2xl': ['clamp(1.5rem, 3vw, 1.875rem)', { lineHeight: '2rem' }],
      '3xl': ['clamp(1.875rem, 4vw, 2.25rem)', { lineHeight: '2.25rem' }],
      '4xl': ['clamp(2.25rem, 5vw, 3rem)', { lineHeight: '2.5rem' }],
    },
    extend: {
      colors: {
        'ink-900': '#0d0f1a',
        'ink-700': '#1c2238',
        'rose-500': '#ff5c8d',
        'brand-violet': '#8b5cf6',
        'brand-pink': '#ff79c6',
        'brand-gradient-start': '#ff79c6',
        'brand-gradient-end': '#8b5cf6',
        'muted-500': '#94a3b8',
      },
      spacing: {
        'safe-top': 'max(1rem, env(safe-area-inset-top))',
        'safe-bottom': 'max(1rem, env(safe-area-inset-bottom))',
      },
      lineHeight: {
        'tight': '1.2',
        'snug': '1.375',
        'normal': '1.5',
        'relaxed': '1.625',
        'loose': '2',
      },
      borderRadius: {
        '3xl': '1.5rem',
      },
      boxShadow: {
        'card-lg': '0 20px 60px rgba(15,23,42,0.08)',
        'active-pill': '0 10px 30px rgba(139,92,246,0.16)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'var(--font-sans)', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'SFMono-Regular', 'monospace'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  corePlugins: {
    // Disable unused core plugins to reduce CSS output
    aspectRatio: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    blur: false,
    brightness: false,
    contrast: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
  },
  plugins: [],
};